# Generated by Django 5.0.3 on 2024-04-29 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stationary', '0003_registrationdata_user_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RegistrationData',
        ),
    ]
