from django.urls import path
from . import views 
from .views import generate_pdf

urlpatterns = [
    path('home/', views.user_profile2, name='home'),
    path('user_profile2/', views.user_profile2, name='user_profile2'),
    path('about/', views.about, name='about'),
    path('addtocart/', views.view_cart, name='addtocart'),
    path('Ball_Pens/', views.Ball_Pens, name='Ball_Pens'),
    path('contact/', views.contact, name='contact'),
    path('Erasers/', views.Erasers, name='Erasers'),
    path('Folders_Fillings/', views.Folders_Fillings, name='Folders_Fillings'),
    path('pen_fountain/', views.pen_fountain, name='pen_fountain'),
    path('Gel_Pens/', views.Gel_Pens, name='Gel_Pens'),
    # path('Gel_Pen/', views.Gel_Pen, name='Gel_Pen'),
    path('highlighter/', views.highlighter, name='highlighter'),
    path('Memo_Blocks/', views.Memo_Blocks, name='Memo_Blocks'),
    path('notebooks/', views.notebooks, name='notebooks'),
    path('notepads/', views.notepads, name='notepads'),
    path('organizers/', views.organizers, name='organizers'),
    path('Paperclips/', views.Paperclips, name='Paperclips'),
    path('Premium_Gel_Pens/', views.Premium_Gel_Pens, name='Premium_Gel_Pens'),
    path('Roller_Ball_Pens/', views.Roller_Ball_Pens, name='Roller_Ball_Pens'),
    path('Sharpener/', views.Shopners, name='Sharpener'),
    path('Staplers/', views.Staplers, name='Staplers'),
    path('Sticky_Notes/', views.Sticky_Notes, name='Sticky_Notes'),
    path('todolist/', views.todolist, name='todolist'),
    path('registration/', views.registration, name='registration'),
    path('generate_pdf/', generate_pdf, name='generate_pdf'),
   path('register/', views.register_with_api, name='register'),
   path('login/', views.login_with_api, name='login'),
   path('', views.index2, name='index2'),
    # path('login/', LoginView.as_view(), name='login'),
    path('getproduct/', views.getproduct, name='getproduct'),
    path('aboutus/', views.aboutus, name='aboutus'),
    path('cancelation/', views.cancelation, name='cancelation'),
    path('return_policy/', views.return_policy, name='return_policy'),
    path('refund_policy/', views.refund_policy, name='refund_policy'),
    path('privacy_policy/', views.privacy_policy, name='privacy_policy'),
    path('terms_conditions/', views.terms_conditions, name='terms_conditions'),
    path('shipping_policy/', views.shipping_policy, name='shipping_policy'),
    path('my_account/', views.my_account, name='my_account'),
    path('faq/', views.faq, name='faq'),
    path('Staplers/', views.Staplers, name='Staplers'),
    path('scissors/', views.scissors, name='scissors'),
    path('calculators/', views.calculators, name='calculators'),
    path('files/', views.files, name='files'),
    path('pen_stands/', views.pen_stands, name='pen_stands'),
    path('cutters/', views.cutters, name='cutters'),
    path('paper_clips/', views.Paperclips, name='paper_clips'),
    path('white_board_markers/', views.white_board_markers, name='white_board_markers'),
    path('punches/', views.punches, name='punches'),
    path('tape_dispenser/', views.tape_dispenser, name='tape_dispenser'),
    path('paints/', views.paints, name='paints'),
    path('art_pencils/', views.art_pencils, name='art_pencils'),
    path('brush_pens/', views.brush_pens, name='brush_pens'),
    path('brushes/', views.brushes, name='brushes'),
    path('sketch/', views.sketch, name='sketch'),
    path('download_app/', views.download_app, name='download_app'),
    path('user_profile/', views.user_profile, name='user_profile'),
    path('wishlist/', views.wishlist, name='wishlist'),

    

]
